import fs from "fs";

const EXPANDED_EGGS = [
  // ASDA
  { id: 'asda-eggs-6-med', supermarket: 'asda', title: 'ASDA 6 Free Range Medium Eggs', brand: 'ASDA', tier: 'standard', category: 'dairy-eggs', subCategory: 'eggs', packageSize: 6, packageUnit: 'pack', packageDisplay: '6 pack', price: 1.35, unitPrice: 0.23, unitPriceMeasure: '£/egg', isHealthier: true, isFreeRange: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=200&auto=format&fit=crop&q=60' },
  { id: 'asda-eggs-6-large', supermarket: 'asda', title: 'ASDA 6 Free Range Large Eggs', brand: 'ASDA', tier: 'standard', category: 'dairy-eggs', subCategory: 'eggs', packageSize: 6, packageUnit: 'pack', packageDisplay: '6 pack', price: 1.50, unitPrice: 0.25, unitPriceMeasure: '£/egg', isHealthier: true, isFreeRange: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=200&auto=format&fit=crop&q=60' },
  { id: 'asda-eggs-6-xlarge', supermarket: 'asda', title: 'ASDA 6 Free Range Very Large Eggs', brand: 'ASDA', tier: 'standard', category: 'dairy-eggs', subCategory: 'eggs', packageSize: 6, packageUnit: 'pack', packageDisplay: '6 pack', price: 1.80, unitPrice: 0.30, unitPriceMeasure: '£/egg', isHealthier: true, isFreeRange: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=200&auto=format&fit=crop&q=60' },
  { id: 'asda-eggs-10-mixed', supermarket: 'asda', title: 'ASDA 10 Free Range Mixed Size Eggs', brand: 'ASDA', tier: 'standard', category: 'dairy-eggs', subCategory: 'eggs', packageSize: 10, packageUnit: 'pack', packageDisplay: '10 pack', price: 1.95, unitPrice: 0.20, unitPriceMeasure: '£/egg', isHealthier: true, isFreeRange: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=200&auto=format&fit=crop&q=60' },
  { id: 'asda-eggs-12-med', supermarket: 'asda', title: 'ASDA 12 Free Range Medium Eggs', brand: 'ASDA', tier: 'standard', category: 'dairy-eggs', subCategory: 'eggs', packageSize: 12, packageUnit: 'pack', packageDisplay: '12 pack', price: 2.35, unitPrice: 0.20, unitPriceMeasure: '£/egg', isHealthier: true, isFreeRange: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=200&auto=format&fit=crop&q=60' },
  { id: 'asda-eggs-12-large', supermarket: 'asda', title: 'ASDA 12 Free Range Large Eggs', brand: 'ASDA', tier: 'standard', category: 'dairy-eggs', subCategory: 'eggs', packageSize: 12, packageUnit: 'pack', packageDisplay: '12 pack', price: 2.65, unitPrice: 0.22, unitPriceMeasure: '£/egg', isHealthier: true, isFreeRange: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=200&auto=format&fit=crop&q=60' },
  { id: 'asda-eggs-15-pack', supermarket: 'asda', title: 'ASDA 15 Free Range Medium Eggs', brand: 'ASDA', tier: 'standard', category: 'dairy-eggs', subCategory: 'eggs', packageSize: 15, packageUnit: 'pack', packageDisplay: '15 pack', price: 2.60, unitPrice: 0.17, unitPriceMeasure: '£/egg', isHealthier: true, isFreeRange: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=200&auto=format&fit=crop&q=60' },
  { id: 'asda-eggs-6-organic', supermarket: 'asda', title: 'ASDA 6 Organic Free Range Eggs', brand: 'ASDA', tier: 'premium', category: 'dairy-eggs', subCategory: 'eggs', packageSize: 6, packageUnit: 'pack', packageDisplay: '6 pack', price: 2.10, unitPrice: 0.35, unitPriceMeasure: '£/egg', isHealthier: true, isFreeRange: true, isOrganic: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=200&auto=format&fit=crop&q=60' },
  { id: 'asda-eggs-6-golden', supermarket: 'asda', title: 'ASDA Extra Special 6 Free Range Golden Yolk Corn Fed Eggs', brand: 'ASDA Extra Special', tier: 'premium', category: 'dairy-eggs', subCategory: 'eggs', packageSize: 6, packageUnit: 'pack', packageDisplay: '6 pack', price: 1.95, unitPrice: 0.33, unitPriceMeasure: '£/egg', isHealthier: true, isFreeRange: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=200&auto=format&fit=crop&q=60' },
  { id: 'asda-eggs-15-value', supermarket: 'asda', title: 'Just Essentials by ASDA 15 Eggs', brand: 'Just Essentials', tier: 'value', category: 'dairy-eggs', subCategory: 'eggs', packageSize: 15, packageUnit: 'pack', packageDisplay: '15 pack', price: 1.55, unitPrice: 0.10, unitPriceMeasure: '£/egg', isHealthier: false, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=200&auto=format&fit=crop&q=60' },

  // TESCO
  { id: 'tesco-eggs-6-med', supermarket: 'tesco', title: 'Tesco 6 British Free Range Medium Eggs', brand: 'Tesco', tier: 'standard', category: 'dairy-eggs', subCategory: 'eggs', packageSize: 6, packageUnit: 'pack', packageDisplay: '6 pack', price: 1.40, unitPrice: 0.23, unitPriceMeasure: '£/egg', isHealthier: true, isFreeRange: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=200&auto=format&fit=crop&q=60' },
  { id: 'tesco-eggs-6-large', supermarket: 'tesco', title: 'Tesco 6 British Free Range Large Eggs', brand: 'Tesco', tier: 'standard', category: 'dairy-eggs', subCategory: 'eggs', packageSize: 6, packageUnit: 'pack', packageDisplay: '6 pack', price: 1.55, unitPrice: 0.26, unitPriceMeasure: '£/egg', isHealthier: true, isFreeRange: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=200&auto=format&fit=crop&q=60' },
  { id: 'tesco-eggs-6-xlarge', supermarket: 'tesco', title: 'Tesco 6 British Free Range Very Large Eggs', brand: 'Tesco', tier: 'standard', category: 'dairy-eggs', subCategory: 'eggs', packageSize: 6, packageUnit: 'pack', packageDisplay: '6 pack', price: 1.85, unitPrice: 0.31, unitPriceMeasure: '£/egg', isHealthier: true, isFreeRange: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=200&auto=format&fit=crop&q=60' },
  { id: 'tesco-eggs-10-mixed', supermarket: 'tesco', title: 'Tesco 10 Mixed Weight Free Range Eggs', brand: 'Tesco', tier: 'standard', category: 'dairy-eggs', subCategory: 'eggs', packageSize: 10, packageUnit: 'pack', packageDisplay: '10 pack', price: 1.95, unitPrice: 0.20, unitPriceMeasure: '£/egg', isHealthier: true, isFreeRange: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=200&auto=format&fit=crop&q=60' },
  { id: 'tesco-eggs-12-med', supermarket: 'tesco', title: 'Tesco 12 British Free Range Medium Eggs', brand: 'Tesco', tier: 'standard', category: 'dairy-eggs', subCategory: 'eggs', packageSize: 12, packageUnit: 'pack', packageDisplay: '12 pack', price: 2.45, unitPrice: 0.20, unitPriceMeasure: '£/egg', isHealthier: true, isFreeRange: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=200&auto=format&fit=crop&q=60' },
  { id: 'tesco-eggs-12-large', supermarket: 'tesco', title: 'Tesco 12 British Free Range Large Eggs', brand: 'Tesco', tier: 'standard', category: 'dairy-eggs', subCategory: 'eggs', packageSize: 12, packageUnit: 'pack', packageDisplay: '12 pack', price: 2.75, unitPrice: 0.23, unitPriceMeasure: '£/egg', isHealthier: true, isFreeRange: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=200&auto=format&fit=crop&q=60' },
  { id: 'tesco-eggs-15-pack', supermarket: 'tesco', title: 'Tesco 15 British Free Range Medium Eggs', brand: 'Tesco', tier: 'standard', category: 'dairy-eggs', subCategory: 'eggs', packageSize: 15, packageUnit: 'pack', packageDisplay: '15 pack', price: 2.75, unitPrice: 0.18, unitPriceMeasure: '£/egg', isHealthier: true, isFreeRange: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=200&auto=format&fit=crop&q=60' },
  { id: 'tesco-eggs-6-organic', supermarket: 'tesco', title: 'Tesco Organic 6 Free Range Eggs', brand: 'Tesco Organic', tier: 'premium', category: 'dairy-eggs', subCategory: 'eggs', packageSize: 6, packageUnit: 'pack', packageDisplay: '6 pack', price: 2.15, unitPrice: 0.36, unitPriceMeasure: '£/egg', isHealthier: true, isFreeRange: true, isOrganic: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=200&auto=format&fit=crop&q=60' },
  { id: 'tesco-eggs-6-golden', supermarket: 'tesco', title: 'Tesco Finest 6 Free Range Golden Yolk Corn Fed Eggs', brand: 'Tesco Finest', tier: 'premium', category: 'dairy-eggs', subCategory: 'eggs', packageSize: 6, packageUnit: 'pack', packageDisplay: '6 pack', price: 1.95, unitPrice: 0.33, unitPriceMeasure: '£/egg', isHealthier: true, isFreeRange: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=200&auto=format&fit=crop&q=60' },
  { id: 'tesco-eggs-15-value', supermarket: 'tesco', title: 'Tesco Everyday Value 15 Eggs', brand: 'Tesco Everyday', tier: 'value', category: 'dairy-eggs', subCategory: 'eggs', packageSize: 15, packageUnit: 'pack', packageDisplay: '15 pack', price: 1.55, unitPrice: 0.10, unitPriceMeasure: '£/egg', isHealthier: false, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=200&auto=format&fit=crop&q=60' },

  // SAINSBURY'S
  { id: 'sainsburys-eggs-6-med', supermarket: 'sainsburys', title: "Sainsbury's Free Range Medium Eggs x6", brand: "Sainsbury's", tier: 'standard', category: 'dairy-eggs', subCategory: 'eggs', packageSize: 6, packageUnit: 'pack', packageDisplay: '6 pack', price: 1.40, unitPrice: 0.23, unitPriceMeasure: '£/egg', isHealthier: true, isFreeRange: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=200&auto=format&fit=crop&q=60' },
  { id: 'sainsburys-eggs-6-large', supermarket: 'sainsburys', title: "Sainsbury's Free Range Large Eggs x6", brand: "Sainsbury's", tier: 'standard', category: 'dairy-eggs', subCategory: 'eggs', packageSize: 6, packageUnit: 'pack', packageDisplay: '6 pack', price: 1.55, unitPrice: 0.26, unitPriceMeasure: '£/egg', isHealthier: true, isFreeRange: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=200&auto=format&fit=crop&q=60' },
  { id: 'sainsburys-eggs-10-mixed', supermarket: 'sainsburys', title: "Sainsbury's Free Range Mixed Weight Eggs x10", brand: "Sainsbury's", tier: 'standard', category: 'dairy-eggs', subCategory: 'eggs', packageSize: 10, packageUnit: 'pack', packageDisplay: '10 pack', price: 1.95, unitPrice: 0.20, unitPriceMeasure: '£/egg', isHealthier: true, isFreeRange: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=200&auto=format&fit=crop&q=60' },
  { id: 'sainsburys-eggs-12-med', supermarket: 'sainsburys', title: "Sainsbury's Free Range Medium Eggs x12", brand: "Sainsbury's", tier: 'standard', category: 'dairy-eggs', subCategory: 'eggs', packageSize: 12, packageUnit: 'pack', packageDisplay: '12 pack', price: 2.45, unitPrice: 0.20, unitPriceMeasure: '£/egg', isHealthier: true, isFreeRange: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=200&auto=format&fit=crop&q=60' },
  { id: 'sainsburys-eggs-12-large', supermarket: 'sainsburys', title: "Sainsbury's Free Range Large Eggs x12", brand: "Sainsbury's", tier: 'standard', category: 'dairy-eggs', subCategory: 'eggs', packageSize: 12, packageUnit: 'pack', packageDisplay: '12 pack', price: 2.75, unitPrice: 0.23, unitPriceMeasure: '£/egg', isHealthier: true, isFreeRange: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=200&auto=format&fit=crop&q=60' },
  { id: 'sainsburys-eggs-15-pack', supermarket: 'sainsburys', title: "Sainsbury's Free Range Medium Eggs x15", brand: "Sainsbury's", tier: 'standard', category: 'dairy-eggs', subCategory: 'eggs', packageSize: 15, packageUnit: 'pack', packageDisplay: '15 pack', price: 2.75, unitPrice: 0.18, unitPriceMeasure: '£/egg', isHealthier: true, isFreeRange: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=200&auto=format&fit=crop&q=60' },
  { id: 'sainsburys-eggs-6-organic', supermarket: 'sainsburys', title: "Sainsbury's SO Organic Free Range Eggs x6", brand: "Sainsbury's SO Organic", tier: 'premium', category: 'dairy-eggs', subCategory: 'eggs', packageSize: 6, packageUnit: 'pack', packageDisplay: '6 pack', price: 2.15, unitPrice: 0.36, unitPriceMeasure: '£/egg', isHealthier: true, isFreeRange: true, isOrganic: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=200&auto=format&fit=crop&q=60' },
  { id: 'sainsburys-eggs-6-golden', supermarket: 'sainsburys', title: "Sainsbury's Taste the Difference Golden Yolk Eggs x6", brand: "Taste the Difference", tier: 'premium', category: 'dairy-eggs', subCategory: 'eggs', packageSize: 6, packageUnit: 'pack', packageDisplay: '6 pack', price: 1.95, unitPrice: 0.33, unitPriceMeasure: '£/egg', isHealthier: true, isFreeRange: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=200&auto=format&fit=crop&q=60' },
  { id: 'sainsburys-eggs-15-value', supermarket: 'sainsburys', title: 'Stamford Street Co. 15 Eggs', brand: 'Stamford Street', tier: 'value', category: 'dairy-eggs', subCategory: 'eggs', packageSize: 15, packageUnit: 'pack', packageDisplay: '15 pack', price: 1.55, unitPrice: 0.10, unitPriceMeasure: '£/egg', isHealthier: false, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=200&auto=format&fit=crop&q=60' },

  // MORRISONS
  { id: 'morrisons-eggs-6-med', supermarket: 'morrisons', title: 'Morrisons 6 Free Range Medium Eggs', brand: 'Morrisons', tier: 'standard', category: 'dairy-eggs', subCategory: 'eggs', packageSize: 6, packageUnit: 'pack', packageDisplay: '6 pack', price: 1.40, unitPrice: 0.23, unitPriceMeasure: '£/egg', isHealthier: true, isFreeRange: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=200&auto=format&fit=crop&q=60' },
  { id: 'morrisons-eggs-6-large', supermarket: 'morrisons', title: 'Morrisons 6 Free Range Large Eggs', brand: 'Morrisons', tier: 'standard', category: 'dairy-eggs', subCategory: 'eggs', packageSize: 6, packageUnit: 'pack', packageDisplay: '6 pack', price: 1.55, unitPrice: 0.26, unitPriceMeasure: '£/egg', isHealthier: true, isFreeRange: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=200&auto=format&fit=crop&q=60' },
  { id: 'morrisons-eggs-12-med', supermarket: 'morrisons', title: 'Morrisons 12 Free Range Medium Eggs', brand: 'Morrisons', tier: 'standard', category: 'dairy-eggs', subCategory: 'eggs', packageSize: 12, packageUnit: 'pack', packageDisplay: '12 pack', price: 2.40, unitPrice: 0.20, unitPriceMeasure: '£/egg', isHealthier: true, isFreeRange: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=200&auto=format&fit=crop&q=60' },
  { id: 'morrisons-eggs-12-large', supermarket: 'morrisons', title: 'Morrisons 12 Free Range Large Eggs', brand: 'Morrisons', tier: 'standard', category: 'dairy-eggs', subCategory: 'eggs', packageSize: 12, packageUnit: 'pack', packageDisplay: '12 pack', price: 2.70, unitPrice: 0.23, unitPriceMeasure: '£/egg', isHealthier: true, isFreeRange: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=200&auto=format&fit=crop&q=60' },
  { id: 'morrisons-eggs-15-pack', supermarket: 'morrisons', title: 'Morrisons 15 Free Range Eggs', brand: 'Morrisons', tier: 'standard', category: 'dairy-eggs', subCategory: 'eggs', packageSize: 15, packageUnit: 'pack', packageDisplay: '15 pack', price: 2.70, unitPrice: 0.18, unitPriceMeasure: '£/egg', isHealthier: true, isFreeRange: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=200&auto=format&fit=crop&q=60' },
  { id: 'morrisons-eggs-6-organic', supermarket: 'morrisons', title: 'Morrisons Organic 6 Free Range Eggs', brand: 'Morrisons Organic', tier: 'premium', category: 'dairy-eggs', subCategory: 'eggs', packageSize: 6, packageUnit: 'pack', packageDisplay: '6 pack', price: 2.10, unitPrice: 0.35, unitPriceMeasure: '£/egg', isHealthier: true, isFreeRange: true, isOrganic: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=200&auto=format&fit=crop&q=60' },
  { id: 'morrisons-eggs-15-value', supermarket: 'morrisons', title: 'Morrisons Savers 15 Eggs', brand: 'Morrisons Savers', tier: 'value', category: 'dairy-eggs', subCategory: 'eggs', packageSize: 15, packageUnit: 'pack', packageDisplay: '15 pack', price: 1.50, unitPrice: 0.10, unitPriceMeasure: '£/egg', isHealthier: false, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=200&auto=format&fit=crop&q=60' },

  // ALDI
  { id: 'aldi-eggs-6-med', supermarket: 'aldi', title: 'Merevale 6 British Free Range Medium Eggs', brand: 'Merevale', tier: 'standard', category: 'dairy-eggs', subCategory: 'eggs', packageSize: 6, packageUnit: 'pack', packageDisplay: '6 pack', price: 1.29, unitPrice: 0.22, unitPriceMeasure: '£/egg', isHealthier: true, isFreeRange: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=200&auto=format&fit=crop&q=60' },
  { id: 'aldi-eggs-6-large', supermarket: 'aldi', title: 'Merevale 6 British Free Range Large Eggs', brand: 'Merevale', tier: 'standard', category: 'dairy-eggs', subCategory: 'eggs', packageSize: 6, packageUnit: 'pack', packageDisplay: '6 pack', price: 1.45, unitPrice: 0.24, unitPriceMeasure: '£/egg', isHealthier: true, isFreeRange: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=200&auto=format&fit=crop&q=60' },
  { id: 'aldi-eggs-10-mixed', supermarket: 'aldi', title: 'Merevale 10 British Free Range Mixed Weight Eggs', brand: 'Merevale', tier: 'standard', category: 'dairy-eggs', subCategory: 'eggs', packageSize: 10, packageUnit: 'pack', packageDisplay: '10 pack', price: 1.85, unitPrice: 0.19, unitPriceMeasure: '£/egg', isHealthier: true, isFreeRange: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=200&auto=format&fit=crop&q=60' },
  { id: 'aldi-eggs-12-med', supermarket: 'aldi', title: 'Merevale 12 British Free Range Medium Eggs', brand: 'Merevale', tier: 'standard', category: 'dairy-eggs', subCategory: 'eggs', packageSize: 12, packageUnit: 'pack', packageDisplay: '12 pack', price: 2.25, unitPrice: 0.19, unitPriceMeasure: '£/egg', isHealthier: true, isFreeRange: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=200&auto=format&fit=crop&q=60' },
  { id: 'aldi-eggs-12-large', supermarket: 'aldi', title: 'Merevale 12 British Free Range Large Eggs', brand: 'Merevale', tier: 'standard', category: 'dairy-eggs', subCategory: 'eggs', packageSize: 12, packageUnit: 'pack', packageDisplay: '12 pack', price: 2.55, unitPrice: 0.21, unitPriceMeasure: '£/egg', isHealthier: true, isFreeRange: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=200&auto=format&fit=crop&q=60' },
  { id: 'aldi-eggs-15-value', supermarket: 'aldi', title: 'Everyday Essentials 15 Eggs', brand: 'Everyday Essentials', tier: 'value', category: 'dairy-eggs', subCategory: 'eggs', packageSize: 15, packageUnit: 'pack', packageDisplay: '15 pack', price: 1.45, unitPrice: 0.10, unitPriceMeasure: '£/egg', isHealthier: false, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=200&auto=format&fit=crop&q=60' },
  { id: 'aldi-eggs-6-organic', supermarket: 'aldi', title: 'Organic 6 British Free Range Eggs', brand: 'Aldi Organic', tier: 'premium', category: 'dairy-eggs', subCategory: 'eggs', packageSize: 6, packageUnit: 'pack', packageDisplay: '6 pack', price: 1.99, unitPrice: 0.33, unitPriceMeasure: '£/egg', isHealthier: true, isFreeRange: true, isOrganic: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=200&auto=format&fit=crop&q=60' },

  // LIDL
  { id: 'lidl-eggs-6-med', supermarket: 'lidl', title: 'Birchwood 6 British Free Range Medium Eggs', brand: 'Birchwood', tier: 'standard', category: 'dairy-eggs', subCategory: 'eggs', packageSize: 6, packageUnit: 'pack', packageDisplay: '6 pack', price: 1.29, unitPrice: 0.22, unitPriceMeasure: '£/egg', isHealthier: true, isFreeRange: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=200&auto=format&fit=crop&q=60' },
  { id: 'lidl-eggs-6-large', supermarket: 'lidl', title: 'Birchwood 6 British Free Range Large Eggs', brand: 'Birchwood', tier: 'standard', category: 'dairy-eggs', subCategory: 'eggs', packageSize: 6, packageUnit: 'pack', packageDisplay: '6 pack', price: 1.45, unitPrice: 0.24, unitPriceMeasure: '£/egg', isHealthier: true, isFreeRange: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=200&auto=format&fit=crop&q=60' },
  { id: 'lidl-eggs-10-mixed', supermarket: 'lidl', title: 'Birchwood 10 British Free Range Mixed Weight Eggs', brand: 'Birchwood', tier: 'standard', category: 'dairy-eggs', subCategory: 'eggs', packageSize: 10, packageUnit: 'pack', packageDisplay: '10 pack', price: 1.85, unitPrice: 0.19, unitPriceMeasure: '£/egg', isHealthier: true, isFreeRange: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=200&auto=format&fit=crop&q=60' },
  { id: 'lidl-eggs-12-med', supermarket: 'lidl', title: 'Birchwood 12 British Free Range Medium Eggs', brand: 'Birchwood', tier: 'standard', category: 'dairy-eggs', subCategory: 'eggs', packageSize: 12, packageUnit: 'pack', packageDisplay: '12 pack', price: 2.25, unitPrice: 0.19, unitPriceMeasure: '£/egg', isHealthier: true, isFreeRange: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=200&auto=format&fit=crop&q=60' },
  { id: 'lidl-eggs-12-large', supermarket: 'lidl', title: 'Birchwood 12 British Free Range Large Eggs', brand: 'Birchwood', tier: 'standard', category: 'dairy-eggs', subCategory: 'eggs', packageSize: 12, packageUnit: 'pack', packageDisplay: '12 pack', price: 2.55, unitPrice: 0.21, unitPriceMeasure: '£/egg', isHealthier: true, isFreeRange: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=200&auto=format&fit=crop&q=60' },
  { id: 'lidl-eggs-15-value', supermarket: 'lidl', title: 'Simply 15 Eggs', brand: 'Simply', tier: 'value', category: 'dairy-eggs', subCategory: 'eggs', packageSize: 15, packageUnit: 'pack', packageDisplay: '15 pack', price: 1.45, unitPrice: 0.10, unitPriceMeasure: '£/egg', isHealthier: false, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=200&auto=format&fit=crop&q=60' },
  { id: 'lidl-eggs-6-organic', supermarket: 'lidl', title: 'Birchwood Organic 6 Free Range Eggs', brand: 'Birchwood Organic', tier: 'premium', category: 'dairy-eggs', subCategory: 'eggs', packageSize: 6, packageUnit: 'pack', packageDisplay: '6 pack', price: 1.99, unitPrice: 0.33, unitPriceMeasure: '£/egg', isHealthier: true, isFreeRange: true, isOrganic: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=200&auto=format&fit=crop&q=60' },

  // ICELAND
  { id: 'iceland-eggs-6-large', supermarket: 'iceland', title: 'Iceland 6 Free Range Large Eggs', brand: 'Iceland', tier: 'standard', category: 'dairy-eggs', subCategory: 'eggs', packageSize: 6, packageUnit: 'pack', packageDisplay: '6 pack', price: 1.50, unitPrice: 0.25, unitPriceMeasure: '£/egg', isHealthier: true, isFreeRange: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=200&auto=format&fit=crop&q=60' },
  { id: 'iceland-eggs-10-pack', supermarket: 'iceland', title: 'Iceland 10 Free Range Eggs', brand: 'Iceland', tier: 'standard', category: 'dairy-eggs', subCategory: 'eggs', packageSize: 10, packageUnit: 'pack', packageDisplay: '10 pack', price: 1.90, unitPrice: 0.19, unitPriceMeasure: '£/egg', isHealthier: true, isFreeRange: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=200&auto=format&fit=crop&q=60' },
  { id: 'iceland-eggs-12-pack', supermarket: 'iceland', title: 'Iceland 12 Free Range Medium Eggs', brand: 'Iceland', tier: 'standard', category: 'dairy-eggs', subCategory: 'eggs', packageSize: 12, packageUnit: 'pack', packageDisplay: '12 pack', price: 2.40, unitPrice: 0.20, unitPriceMeasure: '£/egg', isHealthier: true, isFreeRange: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=200&auto=format&fit=crop&q=60' },
  { id: 'iceland-eggs-15-pack', supermarket: 'iceland', title: 'Iceland 15 Class A Eggs', brand: 'Iceland', tier: 'standard', category: 'dairy-eggs', subCategory: 'eggs', packageSize: 15, packageUnit: 'pack', packageDisplay: '15 pack', price: 2.10, unitPrice: 0.14, unitPriceMeasure: '£/egg', isHealthier: false, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?w=200&auto=format&fit=crop&q=60' }
];

const STORES = ['asda', 'tesco', 'sainsburys', 'morrisons', 'iceland', 'aldi', 'lidl'];

const EXPANDED_GREEK_YOGURT = [];
const EXPANDED_MILK = [];
const EXPANDED_POTATOES = [];

for (const store of STORES) {
  const storeName = store.charAt(0).toUpperCase() + store.slice(1);
  const brandName = store === 'asda' ? 'ASDA' : store === 'tesco' ? 'Tesco' : store === 'sainsburys' ? "Sainsbury's" : store === 'morrisons' ? 'Morrisons' : store === 'aldi' ? 'Brooklea' : store === 'lidl' ? 'Milbona' : 'Iceland';

  // Greek Yogurts
  EXPANDED_GREEK_YOGURT.push(
    { id: `${store}-fage-0-500g`, supermarket: store, title: 'Fage Total 0% Fat Authentic Greek Yogurt 500g', brand: 'Fage', tier: 'premium', category: 'dairy-eggs', subCategory: 'yogurt', packageSize: 500, packageUnit: 'g', packageDisplay: '500g', price: 3.25, unitPrice: 6.50, unitPriceMeasure: '£/kg', isHealthier: true, fatPercentage: 0, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=200&auto=format&fit=crop&q=60' },
    { id: `${store}-fage-0-1kg`, supermarket: store, title: 'Fage Total 0% Fat Authentic Greek Yogurt 1kg', brand: 'Fage', tier: 'premium', category: 'dairy-eggs', subCategory: 'yogurt', packageSize: 1000, packageUnit: 'g', packageDisplay: '1kg', price: 5.50, unitPrice: 5.50, unitPriceMeasure: '£/kg', isHealthier: true, fatPercentage: 0, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=200&auto=format&fit=crop&q=60' },
    { id: `${store}-fage-5-500g`, supermarket: store, title: 'Fage Total 5% Authentic Greek Yogurt 500g', brand: 'Fage', tier: 'premium', category: 'dairy-eggs', subCategory: 'yogurt', packageSize: 500, packageUnit: 'g', packageDisplay: '500g', price: 3.25, unitPrice: 6.50, unitPriceMeasure: '£/kg', isHealthier: true, fatPercentage: 5, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=200&auto=format&fit=crop&q=60' },
    { id: `${store}-fage-2-500g`, supermarket: store, title: 'Fage Total 2% Authentic Greek Yogurt 500g', brand: 'Fage', tier: 'premium', category: 'dairy-eggs', subCategory: 'yogurt', packageSize: 500, packageUnit: 'g', packageDisplay: '500g', price: 3.25, unitPrice: 6.50, unitPriceMeasure: '£/kg', isHealthier: true, fatPercentage: 2, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=200&auto=format&fit=crop&q=60' },
    { id: `${store}-own-greek-0-500g`, supermarket: store, title: `${brandName} 0% Fat Authentic Greek Yogurt 500g`, brand: brandName, tier: 'standard', category: 'dairy-eggs', subCategory: 'yogurt', packageSize: 500, packageUnit: 'g', packageDisplay: '500g', price: 1.50, unitPrice: 3.00, unitPriceMeasure: '£/kg', isHealthier: true, fatPercentage: 0, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=200&auto=format&fit=crop&q=60' },
    { id: `${store}-own-greek-0-1kg`, supermarket: store, title: `${brandName} Fat Free Authentic Greek Yogurt 1kg`, brand: brandName, tier: 'standard', category: 'dairy-eggs', subCategory: 'yogurt', packageSize: 1000, packageUnit: 'g', packageDisplay: '1kg', price: 2.50, unitPrice: 2.50, unitPriceMeasure: '£/kg', isHealthier: true, fatPercentage: 0, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=200&auto=format&fit=crop&q=60' },
    { id: `${store}-own-greek-style-0-500g`, supermarket: store, title: `${brandName} Fat Free Greek Style Yogurt 500g`, brand: brandName, tier: 'standard', category: 'dairy-eggs', subCategory: 'yogurt', packageSize: 500, packageUnit: 'g', packageDisplay: '500g', price: 1.10, unitPrice: 2.20, unitPriceMeasure: '£/kg', isHealthier: true, fatPercentage: 0, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=200&auto=format&fit=crop&q=60' },
    { id: `${store}-own-greek-style-1kg`, supermarket: store, title: `${brandName} Greek Style Natural Yogurt 1kg`, brand: brandName, tier: 'standard', category: 'dairy-eggs', subCategory: 'yogurt', packageSize: 1000, packageUnit: 'g', packageDisplay: '1kg', price: 1.75, unitPrice: 1.75, unitPriceMeasure: '£/kg', isHealthier: true, fatPercentage: 5, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=200&auto=format&fit=crop&q=60' },
    { id: `${store}-yeo-greek-0-450g`, supermarket: store, title: 'Yeo Valley Organic 0% Fat Greek Style Yogurt 450g', brand: 'Yeo Valley', tier: 'premium', category: 'dairy-eggs', subCategory: 'yogurt', packageSize: 450, packageUnit: 'g', packageDisplay: '450g', price: 2.00, unitPrice: 4.44, unitPriceMeasure: '£/kg', isHealthier: true, isOrganic: true, fatPercentage: 0, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=200&auto=format&fit=crop&q=60' }
  );

  // Milk Varieties
  EXPANDED_MILK.push(
    { id: `${store}-milk-semi-1pint`, supermarket: store, title: `${brandName} British Fresh Semi-Skimmed Milk 1 Pint (568ml)`, brand: brandName, tier: 'standard', category: 'dairy-eggs', subCategory: 'milk', packageSize: 568, packageUnit: 'ml', packageDisplay: '1 Pint (568ml)', price: 0.90, unitPrice: 1.58, unitPriceMeasure: '£/L', isHealthier: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=200&auto=format&fit=crop&q=60' },
    { id: `${store}-milk-semi-2pint`, supermarket: store, title: `${brandName} British Fresh Semi-Skimmed Milk 2 Pints (1.136L)`, brand: brandName, tier: 'standard', category: 'dairy-eggs', subCategory: 'milk', packageSize: 1136, packageUnit: 'ml', packageDisplay: '2 Pints (1.13L)', price: 1.20, unitPrice: 1.06, unitPriceMeasure: '£/L', isHealthier: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=200&auto=format&fit=crop&q=60' },
    { id: `${store}-milk-semi-4pint`, supermarket: store, title: `${brandName} British Fresh Semi-Skimmed Milk 4 Pints (2.27L)`, brand: brandName, tier: 'standard', category: 'dairy-eggs', subCategory: 'milk', packageSize: 2270, packageUnit: 'ml', packageDisplay: '4 Pints (2.27L)', price: 1.45, unitPrice: 0.64, unitPriceMeasure: '£/L', isHealthier: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=200&auto=format&fit=crop&q=60' },
    { id: `${store}-milk-semi-6pint`, supermarket: store, title: `${brandName} British Fresh Semi-Skimmed Milk 6 Pints (3.4L)`, brand: brandName, tier: 'standard', category: 'dairy-eggs', subCategory: 'milk', packageSize: 3400, packageUnit: 'ml', packageDisplay: '6 Pints (3.4L)', price: 2.15, unitPrice: 0.63, unitPriceMeasure: '£/L', isHealthier: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=200&auto=format&fit=crop&q=60' },
    { id: `${store}-milk-whole-2pint`, supermarket: store, title: `${brandName} British Fresh Whole Milk 2 Pints (1.136L)`, brand: brandName, tier: 'standard', category: 'dairy-eggs', subCategory: 'milk', packageSize: 1136, packageUnit: 'ml', packageDisplay: '2 Pints (1.13L)', price: 1.20, unitPrice: 1.06, unitPriceMeasure: '£/L', isHealthier: false, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=200&auto=format&fit=crop&q=60' },
    { id: `${store}-milk-whole-4pint`, supermarket: store, title: `${brandName} British Fresh Whole Milk 4 Pints (2.27L)`, brand: brandName, tier: 'standard', category: 'dairy-eggs', subCategory: 'milk', packageSize: 2270, packageUnit: 'ml', packageDisplay: '4 Pints (2.27L)', price: 1.45, unitPrice: 0.64, unitPriceMeasure: '£/L', isHealthier: false, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=200&auto=format&fit=crop&q=60' },
    { id: `${store}-milk-skim-2pint`, supermarket: store, title: `${brandName} British Fresh Skimmed Milk 2 Pints (1.136L)`, brand: brandName, tier: 'standard', category: 'dairy-eggs', subCategory: 'milk', packageSize: 1136, packageUnit: 'ml', packageDisplay: '2 Pints (1.13L)', price: 1.20, unitPrice: 1.06, unitPriceMeasure: '£/L', isHealthier: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=200&auto=format&fit=crop&q=60' },
    { id: `${store}-milk-cravendale-2l`, supermarket: store, title: 'Cravendale Pure Filtered Semi-Skimmed Milk 2L', brand: 'Cravendale', tier: 'premium', category: 'dairy-eggs', subCategory: 'milk', packageSize: 2000, packageUnit: 'ml', packageDisplay: '2L', price: 2.20, unitPrice: 1.10, unitPriceMeasure: '£/L', isHealthier: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=200&auto=format&fit=crop&q=60' },
    { id: `${store}-milk-organic-semi-2pint`, supermarket: store, title: `${brandName} Organic British Semi-Skimmed Milk 2 Pints`, brand: `${brandName} Organic`, tier: 'premium', category: 'dairy-eggs', subCategory: 'milk', packageSize: 1136, packageUnit: 'ml', packageDisplay: '2 Pints (1.13L)', price: 1.55, unitPrice: 1.36, unitPriceMeasure: '£/L', isHealthier: true, isOrganic: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=200&auto=format&fit=crop&q=60' },
    { id: `${store}-milk-uht-semi-1l`, supermarket: store, title: `${brandName} UHT Semi-Skimmed Long Life Milk 1L`, brand: brandName, tier: 'standard', category: 'dairy-eggs', subCategory: 'milk', packageSize: 1000, packageUnit: 'ml', packageDisplay: '1L', price: 0.95, unitPrice: 0.95, unitPriceMeasure: '£/L', isHealthier: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1550583724-b2692b85b150?w=200&auto=format&fit=crop&q=60' }
  );

  // Potato Varieties
  EXPANDED_POTATOES.push(
    { id: `${store}-potatoes-baby-1kg`, supermarket: store, title: `${brandName} Baby New Potatoes 1kg`, brand: brandName, tier: 'standard', category: 'produce', subCategory: 'potatoes', packageSize: 1000, packageUnit: 'g', packageDisplay: '1kg', price: 1.00, unitPrice: 1.00, unitPriceMeasure: '£/kg', isHealthier: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=200&auto=format&fit=crop&q=60' },
    { id: `${store}-potatoes-baby-2kg`, supermarket: store, title: `${brandName} Crisp & Sweet Baby Potatoes 2kg`, brand: brandName, tier: 'standard', category: 'produce', subCategory: 'potatoes', packageSize: 2000, packageUnit: 'g', packageDisplay: '2kg', price: 1.95, unitPrice: 0.98, unitPriceMeasure: '£/kg', isHealthier: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=200&auto=format&fit=crop&q=60' },
    { id: `${store}-potatoes-maris-piper-2.5kg`, supermarket: store, title: `${brandName} British Maris Piper Potatoes 2.5kg`, brand: brandName, tier: 'standard', category: 'produce', subCategory: 'potatoes', packageSize: 2500, packageUnit: 'g', packageDisplay: '2.5kg', price: 1.75, unitPrice: 0.70, unitPriceMeasure: '£/kg', isHealthier: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=200&auto=format&fit=crop&q=60' },
    { id: `${store}-potatoes-king-edward-2kg`, supermarket: store, title: `${brandName} British King Edward Potatoes 2kg`, brand: brandName, tier: 'standard', category: 'produce', subCategory: 'potatoes', packageSize: 2000, packageUnit: 'g', packageDisplay: '2kg', price: 1.80, unitPrice: 0.90, unitPriceMeasure: '£/kg', isHealthier: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=200&auto=format&fit=crop&q=60' },
    { id: `${store}-potatoes-charlotte-1kg`, supermarket: store, title: `${brandName} Charlotte Baby Salad Potatoes 1kg`, brand: brandName, tier: 'standard', category: 'produce', subCategory: 'potatoes', packageSize: 1000, packageUnit: 'g', packageDisplay: '1kg', price: 1.25, unitPrice: 1.25, unitPriceMeasure: '£/kg', isHealthier: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=200&auto=format&fit=crop&q=60' },
    { id: `${store}-potatoes-baking-4pack`, supermarket: store, title: `${brandName} British Baking Potatoes 4 Pack`, brand: brandName, tier: 'standard', category: 'produce', subCategory: 'potatoes', packageSize: 1000, packageUnit: 'g', packageDisplay: '4 pack', price: 0.95, unitPrice: 0.95, unitPriceMeasure: '£/kg', isHealthier: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=200&auto=format&fit=crop&q=60' },
    { id: `${store}-potatoes-white-2.5kg`, supermarket: store, title: `${brandName} British White Potatoes 2.5kg`, brand: brandName, tier: 'standard', category: 'produce', subCategory: 'potatoes', packageSize: 2500, packageUnit: 'g', packageDisplay: '2.5kg', price: 1.45, unitPrice: 0.58, unitPriceMeasure: '£/kg', isHealthier: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=200&auto=format&fit=crop&q=60' },
    { id: `${store}-potatoes-red-2kg`, supermarket: store, title: `${brandName} British Red Potatoes 2kg`, brand: brandName, tier: 'standard', category: 'produce', subCategory: 'potatoes', packageSize: 2000, packageUnit: 'g', packageDisplay: '2kg', price: 1.50, unitPrice: 0.75, unitPriceMeasure: '£/kg', isHealthier: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=200&auto=format&fit=crop&q=60' },
    { id: `${store}-potatoes-jersey-750g`, supermarket: store, title: `${brandName} Jersey Royal Baby Salad Potatoes 750g`, brand: brandName, tier: 'premium', category: 'produce', subCategory: 'potatoes', packageSize: 750, packageUnit: 'g', packageDisplay: '750g', price: 1.50, unitPrice: 2.00, unitPriceMeasure: '£/kg', isHealthier: true, inStock: true, imageUrl: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?w=200&auto=format&fit=crop&q=60' }
  );
}

const ALL_EXPANDED = [
  ...EXPANDED_EGGS,
  ...EXPANDED_GREEK_YOGURT,
  ...EXPANDED_MILK,
  ...EXPANDED_POTATOES
];

console.log(`Generated ${ALL_EXPANDED.length} enriched grocery products across Eggs, Greek Yogurt, Milk, and Potatoes for all 7 supermarkets!`);

// Update logic-api catalogData.js and server catalogData.ts
function injectProducts(filePath, isTypeScript = false) {
  let content = fs.readFileSync(filePath, "utf8");
  
  const marker = "export const DEFAULT_INGREDIENT_IDEAS";
  const markerIdx = content.indexOf(marker);
  if (markerIdx === -1) {
    console.error("Could not find marker in", filePath);
    return;
  }

  // Find the "];" right before the marker
  const closingIdx = content.lastIndexOf("];", markerIdx);
  if (closingIdx === -1) {
    console.error("Could not find closing bracket in", filePath);
    return;
  }

  // Format new items
  const formattedItems = ALL_EXPANDED.map(p => {
    return `  {
    id: '${p.id}',
    supermarket: '${p.supermarket}',
    title: ${JSON.stringify(p.title)},
    brand: ${JSON.stringify(p.brand)},
    tier: '${p.tier}',
    category: '${p.category}',
    subCategory: '${p.subCategory}',
    packageSize: ${p.packageSize},
    packageUnit: '${p.packageUnit}',
    packageDisplay: '${p.packageDisplay}',
    price: ${p.price.toFixed(2)},
    unitPrice: ${p.unitPrice.toFixed(2)},
    unitPriceMeasure: '${p.unitPriceMeasure}',
    isHealthier: ${p.isHealthier ? 'true' : 'false'},
    ${p.isFreeRange ? 'isFreeRange: true,\n    ' : ''}${p.isOrganic ? 'isOrganic: true,\n    ' : ''}${p.fatPercentage !== undefined ? `fatPercentage: ${p.fatPercentage},\n    ` : ''}inStock: true,
    productUrl: '',
    imageUrl: '${p.imageUrl}'
  }`;
  }).join(",\n");

  const newContent = content.slice(0, closingIdx) + ",\n  // --- ENRICHED VARIETY CATALOG (Eggs, Greek Yogurt, Milk, Potatoes) ---\n" + formattedItems + "\n" + content.slice(closingIdx);

  fs.writeFileSync(filePath, newContent, "utf8");
  console.log(`✓ Injected ${ALL_EXPANDED.length} items into ${filePath}`);
}

injectProducts("services/logic-api/src/services/catalogData.js", false);
injectProducts("server/src/services/catalogData.ts", true);
